# Generated by Django 5.2.7 on 2025-11-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_pingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingrecord',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pingrecord',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('progress', 'In Progress'),
                    ('success', 'Success'),
                    ('failed', 'Failed'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='pingrecord',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
