# Generated by Django 5.2.7 on 2025-11-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_pingrecord_completed_at_status_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pingrecord',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
